<#--
  Markdown third-party license report for license-maven-plugin.
  Mirrors the data the default text template emits (one row per
  dependency, sorted by artifact name) as a Markdown table, with a
  static narrative header.
-->
# Third-Party Licenses

This project is licensed under the [BSD Zero Clause License](LICENSE) (0BSD).
The dependency table below is generated by the build; do not edit it by hand.
Regenerate with:

    ./mvnw license:aggregate-add-third-party

The four core library modules — `commons`, `heerwisch-api`, `frau-holle` and
`nachtkrapp` — are JDK-only and pull in no third-party runtime code; their only
non-test dependencies are sibling 0BSD modules of this repository.

JFreeChart is the only LGPL-only dependency and the only third-party runtime
dependency in the repository — it is used solely by the `heerwisch-jfreechart`
driver module. It is linked dynamically as a Maven artifact, so downstream
consumers retain their LGPL right to replace it without having to re-license
this project. Consumers that do not need chart rendering can depend on the
other modules and never pull it in.

<#if dependencyMap?size == 0>
This project has no third-party dependencies.
<#else>
## Dependencies

${dependencyMap?size} third-party dependencies across compile, runtime, provided and test scopes:

| Artifact | Coordinates | License | URL |
| --- | --- | --- | --- |
<#list dependencyMap as e>
<#assign project = e.getKey()/>
<#assign licenses = e.getValue()/>
| ${(project.name)!project.artifactId} | `${project.groupId}:${project.artifactId}:${project.version}` | <#list licenses as license>${license}<#if license_has_next>, </#if></#list> | <#if project.url??>[link](${project.url})<#else>—</#if> |
</#list>
</#if>
